# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # to allow creating users' accounts for our Caretakers without need of doing it in RC GUI
    # Please create (or reuse) admin's account and add Personal Access Token, then put these data below
    # DO NOT STORE CREDENTIALS HERE DIRECTLY ANYMORE!
    # Note these credentials should be stored in the Vault
    # https://symfony.com/doc/5.2/configuration/secrets.html
    # Also for dev/test purposes override them with --local flag (dev env only)
    # Sample:
    # php bin/console secrets:set CHAT_ADMIN_ID --local
    # php bin/console secrets:set CHAT_ADMIN_TOKEN --local
    chat_api:
        admin_id: '%env(CHAT_ADMIN_ID)%'
        admin_token: '%env(CHAT_ADMIN_TOKEN)%'
        host: 'http://localhost'
        port: 3000


#    Please save your token carefully as you will no longer be able to view it afterwards.
#Token: 10i_5su_OK_DmdbTqisbzL6iD9eXPLMwotL13BujVvm
#Your user Id: WGEC2eTrDQLwhNeQg


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
