# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    # to allow creating users' accounts for our Caretakers without need of doing it in RC GUI
    # Please create (or reuse) admin's account and add Personal Access Token, then put these data below
    chat_api:
        admin_id: null
        admin_token: null
        host: 'http://localhost'
        port: 3000

    # Below config is sample, it is not used anywhere.
    chat_api_dev_sample:
        admin_token: 'rDCAID0x-jnKhiticF3m6kmlRy25mVA729rC5upGIBq'
        admin_id: 'mLXK2HcnReutJ7rnn'
        host: 'http://localhost'
        port: 3000

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
